name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn --batch-mode --strict-checksums package

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        files: target/surefire-reports/**/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false

    - name: Run SpotBugs from Maven
      run: mvn --batch-mode com.github.spotbugs:spotbugs-maven-plugin:4.0.4:spotbugs -Dspotbugs.xmlOutput=true -Dspotbugs.effort=max

    - name: Publish SpotBugs report
      uses: jwgmeligmeyling/spotbugs-github-action@master
      with:
        path: '**/spotbugsXml.xml'
     
